export const socketEvents = {
  REGISTRY_USER: 'REGISTRY_USER',
  GET_ONLINE_USERS: 'GET_ONLINE_USERS',
  UPDATE_ONLINE_USERS: 'UPDATE_ONLINE_USERS',
  SEND_PRIVATE_MSG: 'SEND_PRIVATE_MSG',
  RECEIVE_PRIVATE_MSG: 'RECEIVE_PRIVATE_MSG'
}
